"""Add unique constraint to prevent duplicate salary records

Revision ID: 809db51f11fa
Revises: b8bfa958a2d9
Create Date: 2025-12-31 12:16:04.129382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '809db51f11fa'
down_revision = 'b8bfa958a2d9'
branch_labels = None
depends_on = None

def upgrade():
    
    # First, check and create enum types if they don't exist
    conn = op.get_bind()
    # Check for expensetype enum
    result = conn.execute("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expensetype')")
    if not result.scalar():
        op.execute("CREATE TYPE expensetype AS ENUM ('FUEL', 'MAINTENANCE', 'PARTS', 'SALARY', 'TRIP', 'OTHER')")
    # Check for incometype enum
    result = conn.execute("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'incometype')")
    if not result.scalar():
        op.execute("CREATE TYPE incometype AS ENUM ('SHIPMENT', 'OTHER')")
    # Check for salarystatus enum
    result = conn.execute("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salarystatus')")
    if not result.scalar():
        op.execute("CREATE TYPE salarystatus AS ENUM ('PENDING', 'PAID', 'PROCESSING')")
       
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('max_quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_code'), ['code'], unique=True)

    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('trn', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_code'), ['code'], unique=True)

    op.create_table('vehicle',
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_volume', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('fuel_tank_capacity', sa.Float(), nullable=True),
    sa.Column('fuel_efficiency', sa.Float(), nullable=True),
    sa.Column('registration_expiry', sa.Date(), nullable=False),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=False),
    sa.Column('insurance_coverage_type', sa.String(length=50), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('last_serviced_odometer', sa.Float(), nullable=False),
    sa.Column('current_odometer', sa.Float(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('average_fuel_consumption', sa.Float(), nullable=False),
    sa.Column('has_gps', sa.Boolean(), nullable=False),
    sa.Column('has_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('has_trailer_hitch', sa.Boolean(), nullable=False),
    sa.Column('has_safety_features', sa.Boolean(), nullable=False),
    sa.Column('special_equipment', sa.Text(), nullable=True),
    sa.Column('registration_copy_url', sa.String(length=500), nullable=True),
    sa.Column('insurance_copy_url', sa.String(length=500), nullable=True),
    sa.Column('vehicle_photos_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicle_vin'), ['vin'], unique=True)

    op.create_table('driver',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emirates_id', sa.String(length=50), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_type', sa.String(length=20), nullable=False),
    sa.Column('license_issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('license_classes', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('current_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('preferred_vehicle_types', sa.String(length=200), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('passport_copy_url', sa.String(length=500), nullable=True),
    sa.Column('license_copy_url', sa.String(length=500), nullable=True),
    sa.Column('id_copy_url', sa.String(length=500), nullable=True),
    sa.Column('medical_certificate_url', sa.String(length=500), nullable=True),
    sa.Column('medical_certificate_expiry', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('special_skills', sa.Text(), nullable=True),
    sa.Column('languages', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_emirates_id'), ['emirates_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_license_number'), ['license_number'], unique=False)

    op.create_table('expense',
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('expense_type', sa.Enum('FUEL', 'MAINTENANCE', 'PARTS', 'SALARY', 'TRIP', 'OTHER', name='expensetype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('vendor_contact', sa.String(length=100), nullable=True),
    sa.Column('vendor_phone', sa.String(length=20), nullable=True),
    sa.Column('vendor_trn', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('parent_expense_id', sa.Integer(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('supporting_docs_url', sa.String(length=500), nullable=True),
    sa.Column('budget_category', sa.String(length=100), nullable=True),
    sa.Column('accounting_period', sa.String(length=10), nullable=True),
    sa.Column('gl_account', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['parent_expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_expense_number'), ['expense_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_expense_reference_number'), ['reference_number'], unique=False)

    op.create_table('fuel_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('fuel_station', sa.String(length=100), nullable=True),
    sa.Column('fuel_efficiency', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('income_number', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('income_type', sa.Enum('SHIPMENT', 'OTHER', name='incometype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_trn', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('parent_income_id', sa.Integer(), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('supporting_docs_url', sa.String(length=500), nullable=True),
    sa.Column('revenue_category', sa.String(length=100), nullable=True),
    sa.Column('accounting_period', sa.String(length=10), nullable=True),
    sa.Column('gl_account', sa.String(length=50), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['parent_income_id'], ['income.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_income_number'), ['income_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_income_reference_number'), ['reference_number'], unique=False)

    op.create_table('shipment_document',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_event',
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_item',
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_route',
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(length=100), nullable=False),
    sa.Column('to_location', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_status_history',
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('service_provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_assignment',
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_performance',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('driving_skill', sa.Integer(), nullable=False),
    sa.Column('safety_compliance', sa.Integer(), nullable=False),
    sa.Column('customer_service', sa.Integer(), nullable=False),
    sa.Column('punctuality', sa.Integer(), nullable=False),
    sa.Column('vehicle_maintenance', sa.Integer(), nullable=False),
    sa.Column('trips_completed', sa.Integer(), nullable=True),
    sa.Column('distance_covered', sa.Float(), nullable=True),
    sa.Column('on_time_deliveries', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('payer', sa.String(length=200), nullable=True),
    sa.Column('payee', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_date', sa.DateTime(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('budget_category', sa.String(length=100), nullable=True),
    sa.Column('accounting_period', sa.String(length=10), nullable=True),
    sa.Column('gl_account', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_number'), ['transaction_number'], unique=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('check_in',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('check_out',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_attendance_date'))
        batch_op.drop_index(batch_op.f('idx_attendance_employee_id'))
        batch_op.drop_constraint(batch_op.f('attendance_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customer_company_name'))
        batch_op.drop_index(batch_op.f('idx_customer_trn'))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('emirates_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('employment_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('join_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('employment_contract_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('basic_salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('housing_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('transportation_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('other_allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('overtime_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('bank_branch',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('sick_leave_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('passport_copy_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('emirates_id_copy_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('visa_copy_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('labor_card_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('employment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_employee_emirates_id'))
        batch_op.drop_index(batch_op.f('idx_employee_name'))
        batch_op.drop_index(batch_op.f('uq_employee_employee_code'))
        batch_op.create_index(batch_op.f('ix_employee_emirates_id'), ['emirates_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_employee_code'), ['employee_code'], unique=True)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('employee_leave', schema=None) as batch_op:
        batch_op.alter_column('leave_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_index(batch_op.f('idx_employee_leave_employee_id'))
        batch_op.drop_constraint(batch_op.f('employee_leave_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'vat'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.drop_index(batch_op.f('idx_invoice_customer_id'))
        batch_op.drop_index(batch_op.f('idx_invoice_invoice_number'))
        batch_op.drop_constraint(batch_op.f('invoice_invoice_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'AED'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
        batch_op.drop_index(batch_op.f('idx_payment_invoice_id'))
        batch_op.drop_index(batch_op.f('idx_payment_reference'))
        batch_op.drop_constraint(batch_op.f('payment_payment_reference_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_payment_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'])

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.alter_column('salary_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('basic_salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('housing_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('transportation_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('other_allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('overtime_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('overtime_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('incentives_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('deductions_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('social_security_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('other_deductions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('gross_salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('total_deductions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PAID', 'PROCESSING', name='salarystatus'),
               nullable=False)
        batch_op.alter_column('working_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('actual_worked_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('absent_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wps_salary_file_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('wps_submission_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('processed_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('processed_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('approved_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('approved_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('salary_slip_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_salary_employee_id'))
        batch_op.create_index(batch_op.f('ix_salary_salary_number'), ['salary_number'], unique=True)
        batch_op.create_unique_constraint('uq_salary_employee_month_year', ['employee_id', 'month', 'year'])
        batch_op.drop_constraint(batch_op.f('salary_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['processed_by'], ['id'])
        batch_op.drop_column('currency')

    with op.batch_alter_table('salary_notification', schema=None) as batch_op:
        batch_op.alter_column('salary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_salary_notification_salary_id'))
        batch_op.drop_index(batch_op.f('idx_salary_notification_status'))
        batch_op.drop_constraint(batch_op.f('salary_notification_salary_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'salary', ['salary_id'], ['id'])

    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shipment_customer_id'))
        batch_op.drop_index(batch_op.f('idx_shipment_tracking_number'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=False)

    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_shipment_tracking_number'), ['tracking_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_shipment_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('salary_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('salary_notification_salary_id_fkey'), 'salary', ['salary_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_salary_notification_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_salary_notification_salary_id'), ['salary_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('response_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('notification_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('salary_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'AED'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('salary_employee_id_fkey'), 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_salary_employee_month_year', type_='unique')
        batch_op.drop_index(batch_op.f('ix_salary_salary_number'))
        batch_op.create_index(batch_op.f('idx_salary_employee_id'), ['employee_id'], unique=False)
        batch_op.alter_column('salary_slip_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('approved_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('approved_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('processed_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('processed_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('wps_submission_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('wps_salary_file_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('absent_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('leave_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('actual_worked_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('working_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAID', 'PROCESSING', name='salarystatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('net_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('total_deductions',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('gross_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('other_deductions',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('social_security_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('deductions_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('incentives_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('overtime_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('overtime_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('overtime_hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('other_allowances',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('transportation_allowance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('housing_allowance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('basic_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('salary_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_payment_reference'))
        batch_op.create_unique_constraint(batch_op.f('payment_payment_reference_key'), ['payment_reference'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_payment_reference'), ['payment_reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_invoice_id'), ['invoice_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'AED'::character varying"))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.create_unique_constraint(batch_op.f('invoice_invoice_number_key'), ['invoice_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_invoice_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'vat'::character varying"))

    with op.batch_alter_table('employee_leave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('employee_leave_employee_id_fkey'), 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_employee_leave_employee_id'), ['employee_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('leave_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_employee_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employee_emirates_id'))
        batch_op.create_index(batch_op.f('uq_employee_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_employee_emirates_id'), ['emirates_id'], unique=True)
        batch_op.alter_column('employment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('blood_group',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('labor_card_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('visa_copy_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('emirates_id_copy_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('passport_copy_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('sick_leave_balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('bank_branch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('overtime_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('other_allowances',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('transportation_allowance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('housing_allowance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('basic_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('employment_contract_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('join_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('employment_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('emirates_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customer_trn'), ['trn'], unique=False)
        batch_op.create_index(batch_op.f('idx_customer_company_name'), ['company_name'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_employee_id_fkey'), 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_attendance_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_date'), ['attendance_date'], unique=False)
        batch_op.alter_column('check_out',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('check_in',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_number'))
        batch_op.drop_index(batch_op.f('ix_transaction_reference_number'))

    op.drop_table('transaction')
    op.drop_table('driver_performance')
    op.drop_table('driver_assignment')
    op.drop_table('vehicle_maintenance')
    op.drop_table('shipment_status_history')
    op.drop_table('shipment_route')
    op.drop_table('shipment_item')
    op.drop_table('shipment_event')
    op.drop_table('shipment_document')
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_reference_number'))
        batch_op.drop_index(batch_op.f('ix_income_income_number'))

    op.drop_table('income')
    op.drop_table('fuel_record')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_reference_number'))
        batch_op.drop_index(batch_op.f('ix_expense_expense_number'))

    op.drop_table('expense')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_license_number'))
        batch_op.drop_index(batch_op.f('ix_driver_employee_id'))
        batch_op.drop_index(batch_op.f('ix_driver_emirates_id'))

    op.drop_table('driver')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicle_registration_number'))

    op.drop_table('vehicle')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_code'))

    op.drop_table('project')
    op.drop_table('supplier')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_code'))

    op.drop_table('service')
    # ### end Alembic commands ###
